test infra workflow edits

diff --git a/.github/workflows/test_infrastructure.yaml b/.github/workflows/test_infrastructure.yaml
--- a/.github/workflows/test_infrastructure.yaml
+++ b/.github/workflows/test_infrastructure.yaml
@@ -35,6 +35,22 @@ jobs:
         with:
           arch: amd64
 
+      - name: Assume AWS IAM Role
+        id: configureCreds
+        uses: aws-actions/configure-aws-credentials@v4.0.1
+        with: 
+          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
+          role-session-name: GitHub_to_AWS_via_FederatedOIDC
+          aws-region: ${{ env.AWS_REGION }}
+        continue-on-error: true
+
+      - name: Assume Role Failure
+        if: steps.configureCreds.outcome == 'failure'
+        run: |
+          echo "job failed"
+          aws sts get-caller-identity
+          exit 1
+
       - name: Create backend config
         id: create_backend
         run: |
@@ -59,29 +75,6 @@ jobs:
 
       - name: get caller identity
         run : aws sts get-caller-identity --no-cli-pager
-
-      - name: Assume AWS IAM Role
-        id: configureCreds
-        uses: aws-actions/configure-aws-credentials@v4.0.1
-        with: 
-          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
-          role-session-name: GitHub_to_AWS_via_FederatedOIDC
-          aws-region: ${{ env.AWS_REGION }}
-        continue-on-error: true
-
-      - name: Assume Role Failure
-        if: steps.configureCreds.outcome == 'failure'
-        run: |
-          echo "job failed"
-          aws sts get-caller-identity
-          exit 1
-
-      # - name: Generate tfstate file
-      #   id: generate_filename
-      #   run: |
-      #     export filename="resume"
-      #     echo "filename ${filename}"
-      #     echo "filename=${filename}.tfstate" >> $GITHUB_OUTPUT
 
       - name: Terraform Plan
         id: plan
