actions workflow changes

diff --git a/.github/workflows/test_lambda.yaml b/.github/workflows/test_lambda.yaml
--- a/.github/workflows/test_lambda.yaml
+++ b/.github/workflows/test_lambda.yaml
@@ -6,6 +6,10 @@ on:
       - 'infrastructure/**'
       - 'frontend/**'
 
+env:
+  AWS_REGION : "us-west-1"
+  AWS_DEFAULT_OUTPUT: json
+
 permissions:
   id-token: write
   contents: read
@@ -22,7 +26,25 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Install Dependencies
+        id: installDependenacies
         run: pip install -r requirements.txt
 
+      - name: Assume AWS IAM Role
+        id: configureCreds
+        uses: aws-actions/configure-aws-credentials@v4.0.1
+        with: 
+          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
+          role-session-name: GitHub_to_AWS_via_FederatedOIDC
+          aws-region: ${{ env.AWS_REGION }}
+        continue-on-error: true
+
+      - name: Assume Role Failure
+        if: steps.configureCreds.outcome == 'failure'
+        run: |
+          echo "job failed"
+          aws sts get-caller-identity
+          exit 1
+          
       - name: Run Test
+        id: runTest
         run: python -m unittest lambda_test.py
